### PR TITLE
Product service

### PR DESCRIPTION
**Pull request by JosepDev23**
Product service, comunications with backend goes brrrrr

### CODE REVIEW

**Comment by JosepDev23** [comment]
also created an interface for our products

**Comment by Dasagho** [comment]
Miss a unique ID or something in the product interface to avoid the console warning key being duplicated on the Consum endpoint. I tried to use the name, but it's repeated.

**Comment by Dasagho** [comment]
fix some css bug

**Comment by Dasagho** [comment]
I was thinking about creating a third repo to store the interfaces in common between our front and back; with this repo, we can avoid the duplicated code between repos.
What do you think?

**Comment by JosepDev23** [comment]
i dont think its a good idea xd

**Comment by JosepDev23** [comment]
also, the files of the React components are comonly named using kebap-case, not PascalCase.

What do u think about that?

I want to unify the cases

**Comment by JosepDev23** [comment]
mongo has unique id, the variable is _id but we did not used it, i will add to our interface

**Comment by Dasagho** [comment]
ok for me

**Pull request merged**
