### PR TITLE
create initial sketch

### PR DESCRIPTION
**Pull request by Dasagho**
First, I have created Supermarket as an enum to speed things up, but I think we would prefer to replace it with an interface. 
Second, I didn't spend many time on the style, so please be gentle.

### CODE REVIEW

**Comment by JosepDev23** [comment]
-Created a component folder
-Added Prettier file
-Removed all global styles

**Comment by JosepDev23** [comment]
added cool cards and navigation

**Comment by JosepDev23** [comment]
please, check out the changes

**Comment by Dasagho** [comment]
I propose moving the components folder to the src folder to avoid mixing the page tree in the app folder with pure react components.

**Comment by JosepDev23** [comment]
fine

**Pull request merged**
